### ISSUE TITLE
Transfer ownership to JSFoundation

### ISSUE THREAD

**Issue by ilyavolodin** [not-an-aardvark/eslint-canary#9] opened 2017-02-27 23:12 UTC
Since all of the projects in ESLint organization are under JSFoundation, we should transfer ownership of this project over as well. @kborchers could you provide the steps necessary to do that?

**Comment by kborchers** [comment] 2017-02-27 23:41
So it looks as if this project was created within the ESLint org after the JSF took ownership of the project, is that correct? If so, technically the JSF already owns this repo and the copyright info in the license is incorrect and just needs to be updated and you're done.

If it was created elsewhere and transferred in, it should not have been transferred in without an explicit assignment. I'll have to talk to legal about the best way to proceed in this scenario but just let me know the sequence of events and we'll go from there.

**Comment by not-an-aardvark** [comment] 2017-02-27 23:46
I created the repo as `not-an-aardvark/eslint-canary` on January 11th. A bit later, I made an [issue](https://github.com/eslint/eslint/issues/8032) to suggest transferring the repo to the eslint organization. On February 16th, the ESLint TSC [decided](https://github.com/eslint/tsc-meetings/blob/32caf1a99636afc1f927f4eb23ea88d4ed1b9caa/notes/2017/2017-02-16.md) to accept that proposal, so I transferred the repo to the eslint organization right after that.

edit: fixed typo (the original repo was `not-an-aardvark/eslint-canary`, not `not-an-aardvark/eslint`.)

**Comment by kborchers** [comment] 2017-02-27 23:52
Hmm, OK. My guess is legal will say that a case could be made that the vote to transfer in will act as a transfer to the JSF but I will double-check and let you know.

**Comment by not-an-aardvark** [comment] 2017-02-27 23:54
Sounds good, thanks! Sorry about the inconvenience -- I hadn't realized that there was an official process for transferring the repo.

**Comment by kborchers** [comment] 2017-02-27 23:59
No worries. We're still working in documenting things like this so we're all learning as we go. 😉

**Comment by platinumazure** [comment] 2017-09-20 15:57
@not-an-aardvark @ilyavolodin @kborchers Did we resolve this?

**Comment by not-an-aardvark** [comment] 2017-09-20 17:18
I'm not sure -- I haven't heard anything about this aside from the contents of this issue.

**Comment by kborchers** [comment] 2017-09-22 21:30
Sorry, this definitely fell off my radar. I have pinged legal on it and will respond ASAP. My apologies again for the delay.

**Comment by kborchers** [comment] 2017-09-22 21:47
Legal has confirmed that since all 3 contributors on the project have signed the CLA, this is ready to close with 1 exception. Please change the copyright line in the LICENSE.md to just `Copyright contributors` and then you are good to go.

**Comment by platinumazure** [comment] 2017-09-25 13:19
@kborchers "Copyright contributors", not "Copyright JS Foundation and other contributors, https://js.foundation" (see https://github.com/eslint/eslint/blob/master/LICENSE#L1)?

**Comment by kborchers** [comment] 2017-09-25 13:27
@platinumazure Correct. In this case, since the copyright was never assigned to the JSF, just licensed via the CLA, we can not claim copyright ownership. In general, we would prefer to do a full assignment with paperwork and everything but decided for this one instance, it was not necessary and wouldn't burden the 3 contributors with the paperwork. Happy to do it if you would prefer consistency, but not necessary.

All of that said, you should always ping the TAC or me before transferring in a repo going forward.

**Comment by platinumazure** [comment] 2017-09-25 14:51
@kborchers Would it cause problems if it said something like "Copyright ESLint team and contributors"? It reads a little more naturally, but if it could raise legal questions about "wait, did the 3 contributors actually transfer copyright to the ESLint team", then we can just leave it at "Copyright contributors".

I don't have a strong preference about consistency (in terms of labeling it as "Copyright JS Foundation"), but others might.

**Comment by kborchers** [comment] 2017-09-25 15:10
We should definitely follow legal's advice here and either do a full IP assignment and use the usual copyright line with JS Foundation in it or just use "Copyright contributors" to avoid any issues.

**Comment by platinumazure** [comment] 2017-09-25 17:33
@kborchers Seems like our TSC should probably evaluate which path they want to take here. We'll ping you if we decide we want to do a full IP assignment. In the meanwhile, would you please read the summary below and advise if I misrepresented anything? Thanks!

# TSC Summary

Kris Borchers from JSF has given us two paths forward to fully resolve the IP/ownership issues around this repository:
* Declare "Copyright contributors" in the copyright file and do nothing further (JSF will not assert copyright and does not need to)
* Do a full IP assignment of this repository to JSF, which requires all committers so far (3 at last count) to fill out paperwork of some sort. Then declare "Copyright JS Foundation and other contributors", same as ESLint itself.

# TSC Question

Which path do we want to take in order to finish (legally) transferring ownership of this repository!

**Comment by kborchers** [comment] 2017-09-25 18:02
@platinumazure LGTM

**Comment by not-an-aardvark** [comment] 2017-10-13 04:19
In [today's TSC meeting](https://gitter.im/eslint/tsc-meetings/archives/2017/10/12), we decided to just use "Copyright contributors".

**Closed as completed** 2017-10-13 05:26 UTC
Labels: question
